resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s

spring:
  cloud:
    gateway:
      routes:
      - id: conferences-service
        uri: lb://conferences-service
        predicates:
          - Path=/api/conference/**
        filters:
          - StripPrefix=2
      - id: users-service
        uri: lb://users-service
        predicates:
          - Path=/api/user/**
        filters:
          - StripPrefix=2
      #- id: oauth-service
      #  uri: lb://oauth-service
      #  predicates:
      #    - Path=/api/security/**
      #  filters:
      #    - StripPrefix=2